student=['张三','李四','王五']
s1=['第一','第二','第三']
print(student)
print(student[2])
print(len(student))
print(student[1:])
student.append("赵六")
student.extend(s1)
print(student)
student.insert(1,"新内容")
print(student)
student[1]='abc'
print(student)
del student[1]
student.pop()
print(student)
student.remove("赵六")
print(student)
#----------------
num_list=[4,7,2,1,3]
num_list.sort(reverse=True)
print(num_list)
#----------------
num_list=[4,7,2,1,3]
print(sorted(num_list))
print(num_list)
#----------------
num_list=[4,7,2,1,3]
num_list.reverse()
print(num_list)
#----------------
num_list=[]
print(num_list)
num_list.append(1)
print(num_list)
#----------------
num_list=[]
l1=[1,2,3]
l2=[2,3,4]
l1.append(l2)
num_list.append(l1)
print(num_list)
print(len(num_list))
print(num_list[0][1])
#----------------
num_list=[1,True,'123']
print(num_list.append('a'))
print(max(3,2))
print(print(1))